#!/usr/bin/env python3
"""
Darwin Bot for BoTTube
======================
An autonomous agent script that interacts with the BoTTube API.
This bot fetches trending videos and performs simple interactions.

Generated by Project Darwin (v0.2)
"""

import os
import time
import requests
import random

# Configuration
API_BASE_URL = os.environ.get("BOTTUBE_URL", "https://bottube.ai/api")
API_KEY = os.environ.get("BOTTUBE_API_KEY")

class BotTubeAgent:
    def __init__(self, api_key):
        self.api_key = api_key
        self.session = requests.Session()
        # Only add auth header if key exists
        if self.api_key:
            self.session.headers.update({
                "X-API-Key": self.api_key
            })
        self.session.headers.update({
            "User-Agent": "Darwin-Bot/0.2"
        })

    def get_trending_videos(self):
        """Fetch trending videos from the public API."""
        try:
            url = f"{API_BASE_URL}/trending"
            print(f"   📡 Fetching: {url}")
            resp = self.session.get(url)
            if resp.status_code == 200:
                return resp.json()
            else:
                print(f"❌ Failed to fetch trending: {resp.status_code}")
                return []
        except Exception as e:
            print(f"❌ Error fetching trending: {e}")
            return []

    def run_daily_routine(self):
        """Performs a simple daily routine of browsing content."""
        print("🤖 Darwin Bot starting daily routine...")

        # 1. Browse Trending
        videos = self.get_trending_videos()
        if not videos:
            print("   ⚠️ No videos found or API error.")
            # Simulate some data for demo purposes if API is down/unreachable
            videos = [{"title": "Demo Video 1", "id": "1"}, {"title": "AI Agent Demo", "id": "2"}]

        print(f"   📺 Found {len(videos)} videos in feed.")

        # 2. Watch a random video (Simulation)
        if videos:
            target_video = random.choice(videos)
            title = target_video.get('title', 'Unknown')
            print(f"   👀 Watching: '{title}'...")
            time.sleep(1.0) # Simulate watch time
            print(f"   ✅ Finished watching '{title}'.")

        print("🤖 Routine complete.")

def main():
    print("--- Darwin Bot v0.2 ---")
    if not API_KEY:
        print("⚠️  BOTTUBE_API_KEY environment variable not set.")
        print("   Running in public read-only mode.")

    bot = BotTubeAgent(api_key=API_KEY)
    bot.run_daily_routine()

if __name__ == "__main__":
    main()
