# SPDX-License-Identifier: MIT
"""Pre-existing test failures quarantined when CI was made fail-closed.

Each entry is an exact pytest node ID. tests/conftest.py marks it
``xfail(strict=True)``, so:
  * it still runs, and CI stays green while it keeps failing;
  * if it starts passing, CI goes red (XPASS strict) - delete the entry;
  * if the test is renamed/removed, collection fails - delete the entry.

Tracking issue: see QUARANTINE_ISSUE. Do not add entries to hide new failures.
"""

QUARANTINE_ISSUE = "https://github.com/Scottcjn/bottube/issues/2311"

_R = {
    'R00': 'trust&safety migration columns (is_suspended, tos_accepted_*) not added on the fresh-db-then-retry path the test drives',
    'R01': '/api/activity/feed is not a route on main (404)',
    'R02': '/api/conversations/<a>/<b> returns 404 (no JSON body) for the agents the test creates',
    'R03': 'watch page no longer renders interaction-indicators badges / tooltips',
    'R04': "/api/dashboard/analytics response has no 'totals' key (response shape changed)",
    'R05': 'creator analytics endpoints return 401 for the session the test logs in with (session user_id not accepted)',
    'R06': "top_videos rows have no 'thumbnail' key",
    'R07': "top_videos rows have no 'trend' key",
    'R08': '/analytics answers 308 (route moved/slash redirect) where the test expects 200',
    'R09': '/analytics answers 308 (route moved/slash redirect) where the test expects 302/200',
    'R10': 'explore.html:126 submit button has no action description (real a11y gap)',
    'R11': 'off-ramp disabled by #2222 (securities-law compliance): endpoint now returns 410 OFFRAMP_DISABLED before the behaviour this test exercises; rewrite or retire once bridge policy is final',
    'R12': 'web tip with two collaborators splits 0.12 where the test expects 0.04 per collaborator; not investigated',
    'R13': 'off-ramp disabled by #2222 (securities-law compliance): endpoint now returns 410 OFFRAMP_DISABLED before the behaviour this test exercises; rewrite or retire once bridge policy is final (/bridge page itself returns 410)',
    'R14': 'fixture is broken: requests hit 404 and the app has no 404.html on its template path; setup calls get_db() outside an app context',
    'R15': '/api/collaborations* routes are not defined on main (404); feature tests without the feature',
    'R16': 'test sets mock_db_path.__class__ on a PosixPath (TypeError); /api/collaborations routes also absent',
    'R17': 'test schema lacks videos.is_removed used by the agent directory',
    'R18': 'test schema lacks videos.is_removed used by /api/discover/for-you',
    'R19': 'search returns no results for freshly inserted fixture videos (fixture rows likely miss a visibility column the search filter now requires)',
    'R20': 'ergo deposit queries users.erg_address, which the test schema lacks',
    'R21': 'unknown agent gets 403 (auth check runs before existence check); test expects 404',
    'R22': 'POSSIBLE BUG: browser notification preferences accept non-boolean values (200, expected 400)',
    'R23': 'POSSIBLE BUG: malformed read selectors still mark a notification read (unread count 1, expected 2)',
    'R24': "order-dependent: passes when run alone, fails in the full suite because an earlier module imports bottube_server first and this module's import-time DB bootstrap never runs (no such table: agents / 500)",
    'R25': 'test calls bottube_server._append_playlist_item which does not exist on main',
    'R26': 'comment-vote stale-snapshot recovery raises UNIQUE constraint on comment_votes',
    'R27': "POSSIBLE BUG: referral first-upload / hit-window accounting under the test's simulated concurrent stale reads counts wrong",
    'R28': 'search category filter / pagination state not preserved as the test expects',
    'R29': "search suggestions response shape changed (extra 'query', different nesting)",
    'R30': "studio poll JS no longer emits the expected 'Done!' message",
    'R31': 'subscribe JS handler contract changed (status text / count shape); test parses template JS',
    'R32': 'poller queue/adapter behaviour diverged from test expectations (override count, dequeue, adapter reload); not investigated',
    'R33': "order-dependent: passes when run alone, fails in the full suite because an earlier module imports bottube_server first and this module's import-time DB bootstrap never runs (routes 500 on missing tables)",
    'R34': 'POSSIBLE BUG: tip routes accept a structured (non-string) message with 200 instead of 400',
    'R35': 'uploaded video is not visible via /api/videos, detail or agent profile right after upload (likely held for moderation/processing); not investigated',
    'R36': 'POSSIBLE BUG: /me, /wallet, /settings answer 200 for anonymous users instead of redirecting to /login',
    'R37': 'POSSIBLE BUG: updating a video with an empty description does not clear it',
    'R38': '/api/videos/<id>/tips looks up the video (404) before validating pagination (test expects 400 first)',
}

QUARANTINED = {
    'tests/test_admin_key_env.py::test_trust_safety_schema_supports_fresh_db_then_retries_agent_migration': _R['R00'],
    'tests/test_agent_interaction_visibility.py::TestActivityFeed::test_activity_feed_agent_filter': _R['R01'],
    'tests/test_agent_interaction_visibility.py::TestActivityFeed::test_activity_feed_event_shape': _R['R01'],
    'tests/test_agent_interaction_visibility.py::TestActivityFeed::test_activity_feed_limit': _R['R01'],
    'tests/test_agent_interaction_visibility.py::TestActivityFeed::test_activity_feed_respects_since': _R['R01'],
    'tests/test_agent_interaction_visibility.py::TestActivityFeed::test_activity_feed_returns_events': _R['R01'],
    'tests/test_agent_interaction_visibility.py::TestConversationsView::test_conversations_agent_not_found': _R['R02'],
    'tests/test_agent_interaction_visibility.py::TestConversationsView::test_conversations_between_agents': _R['R02'],
    'tests/test_agent_interaction_visibility.py::TestConversationsView::test_conversations_chronological_order': _R['R02'],
    'tests/test_agent_interaction_visibility.py::TestConversationsView::test_conversations_empty': _R['R02'],
    'tests/test_agent_interaction_visibility.py::TestConversationsView::test_conversations_message_shape': _R['R02'],
    'tests/test_agent_interaction_visibility.py::TestWatchPageAccessibility::test_watch_page_badge_tooltips': _R['R03'],
    'tests/test_agent_interaction_visibility.py::TestWatchPageAccessibility::test_watch_page_renders_interaction_badges': _R['R03'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiCoreMetrics::test_analytics_api_video_count': _R['R04'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiCoreMetrics::test_analytics_api_view_count': _R['R04'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiCoreMetrics::test_creator_analytics_blueprint_uses_public_video_ids': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiCoreMetrics::test_creator_analytics_exports_engagement_csv': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiEmptyState::test_analytics_api_empty_for_new_user': _R['R04'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_accepts_boundary_limits[1]': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_accepts_boundary_limits[50]': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_includes_thumbnail': _R['R06'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_rejects_invalid_metric': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_rejects_non_integer_limit': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_rejects_out_of_range_limit[-1]': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_rejects_out_of_range_limit[0]': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_rejects_out_of_range_limit[51]': _R['R05'],
    'tests/test_analytics_dashboard.py::TestAnalyticsApiTopVideos::test_analytics_api_top_videos_trend_calculation': _R['R07'],
    'tests/test_analytics_dashboard.py::TestAnalyticsDashboardIntegration::test_full_analytics_flow': _R['R08'],
    'tests/test_analytics_dashboard.py::TestAnalyticsPageAccess::test_analytics_page_accessible_when_logged_in': _R['R09'],
    'tests/test_analytics_dashboard.py::TestAnalyticsPageAccess::test_analytics_page_requires_login': _R['R09'],
    'tests/test_aria_labels.py::TestAriaLabelCoverage::test_submit_buttons_have_action_labels': _R['R10'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[-1]': _R['R11'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[0]': _R['R11'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[Infinity]': _R['R11'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[NaN]': _R['R11'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[True]': _R['R11'],
    'tests/test_banano_amount_validation.py::test_ban_withdraw_rejects_invalid_amounts_without_writes[abc]': _R['R11'],
    'tests/test_banano_tip_pending_withdrawal.py::test_inflight_or_ambiguous_withdrawal_stays_reserved[processing]': _R['R11'],
    'tests/test_banano_tip_pending_withdrawal.py::test_inflight_or_ambiguous_withdrawal_stays_reserved[uncertain]': _R['R11'],
    'tests/test_banano_tip_pending_withdrawal.py::test_tip_rejected_after_full_balance_is_withdrawn': _R['R11'],
    'tests/test_banano_tip_pending_withdrawal.py::test_tip_still_allowed_within_the_unwithdrawn_remainder': _R['R11'],
    'tests/test_banano_withdrawal_atomicity.py::test_concurrent_withdrawals_cannot_reserve_more_than_balance': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_deposit_rejects_non_object_json': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_deposit_rejects_non_string_tx_hash': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_history_rejects_invalid_limit[-5]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_history_rejects_invalid_limit[0]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_history_rejects_invalid_limit[1.5]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_history_rejects_invalid_limit[not-a-number]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_history_rejects_invalid_limit[true]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_finite_amounts[Infinity]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_finite_amounts[NaN]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_finite_amounts[True]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_finite_amounts[abc]': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_object_json': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_base_bridge_withdraw_rejects_non_string_to_address': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_rejected_base_bridge_withdrawal_does_not_queue_or_debit': _R['R11'],
    'tests/test_base_wrtc_bridge_validation.py::test_uncertain_base_withdrawal_remains_in_bridge_liabilities': _R['R11'],
    'tests/test_bounty_2161_collab_tip_split.py::TestCollabTipSplit::test_web_tip_with_two_collaborators_uses_same_split': _R['R12'],
    'tests/test_bridge_route_not_shadowed.py::test_bridge_page_renders_the_contract_address_block': _R['R13'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_customization_requires_auth': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_get_customization_defaults': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_get_public_customization': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_get_public_customization_not_found': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_update_customization_invalid_banner_url': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_update_customization_invalid_color': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_update_customization_invalid_color_format': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_update_customization_partial': _R['R14'],
    'tests/test_channel_customization.py::TestChannelCustomization::test_update_customization_valid': _R['R14'],
    'tests/test_channel_customization.py::TestCustomizationIntegration::test_channel_page_includes_customization': _R['R14'],
    'tests/test_channel_customization.py::TestCustomizationIntegration::test_pinned_videos_appear_on_channel': _R['R14'],
    'tests/test_channel_customization.py::TestCustomizationIntegration::test_watch_page_includes_creator_customization': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_get_pinned_videos_public': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_pin_video': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_pin_video_already_pinned': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_pin_video_max_limit': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_pin_video_not_owned': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_pin_video_requires_auth': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_reorder_pinned_videos': _R['R14'],
    'tests/test_channel_customization.py::TestPinnedVideos::test_unpin_video': _R['R14'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_add_playlist_collaborator': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_add_video_not_yours': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_add_video_to_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_collaboration_rate_limits': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_create_collaboration_basic': _R['R16'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_create_collaboration_invalid_type': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_create_collaboration_missing_title': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_create_collaboration_with_participants': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_delete_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_duplicate_invite_prevented': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_collab_notifications': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_my_collab_invites': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_my_collaborations': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_my_collaborative_playlists': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_get_playlist_collaborators': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_invite_self_to_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_invite_to_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_leave_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_mark_collab_notifications_read': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_owner_cannot_leave_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_remove_collab_participant': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_remove_playlist_collaborator': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_respond_to_collab_invite_accept': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_respond_to_collab_invite_decline': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_update_collaboration': _R['R15'],
    'tests/test_collaboration.py::TestCollaborationFeatures::test_update_collaboration_unauthorized': _R['R15'],
    'tests/test_discover_agent_directory_pagination.py::test_agent_directory_applies_documented_offset': _R['R17'],
    'tests/test_discover_for_you_session.py::test_for_you_uses_signed_in_web_session_without_api_key': _R['R18'],
    'tests/test_discoverability.py::TestSearchEnhancements::test_search_agent_filter': _R['R19'],
    'tests/test_discoverability.py::TestSearchEnhancements::test_search_relevance_sort': _R['R19'],
    'tests/test_discoverability.py::TestSearchEnhancements::test_search_tag_filter': _R['R19'],
    'tests/test_discoverability.py::TestSearchPageUI::test_search_page_pagination': _R['R19'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[-1]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[0]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[Infinity]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[NaN]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[True]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_invalid_amount_without_queue_or_debit[abc]': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_non_object_json': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_ergo_withdraw_rejects_non_string_address': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_process_withdrawals_rejects_non_object_json': _R['R11'],
    'tests/test_ergo_bridge_validation.py::test_process_withdrawals_rejects_non_string_tx_id': _R['R11'],
    'tests/test_ergo_deposit_credits_rtc.py::test_deposit_credits_rtc_and_writes_earnings_row': _R['R20'],
    'tests/test_mood_write_authorization.py::test_unknown_agent_is_404_not_403': _R['R21'],
    'tests/test_notification_preference_boolean_validation.py::test_browser_notification_preferences_reject_non_booleans': _R['R22'],
    'tests/test_notifications.py::test_notification_read_routes_reject_other_malformed_selectors[payload0]': _R['R23'],
    'tests/test_notifications.py::test_notification_read_routes_reject_other_malformed_selectors[payload1]': _R['R23'],
    'tests/test_notifications.py::test_notification_read_routes_reject_other_malformed_selectors[payload2]': _R['R23'],
    'tests/test_notifications.py::test_notification_read_routes_reject_other_malformed_selectors[payload3]': _R['R23'],
    'tests/test_notifications.py::test_notification_read_routes_reject_other_malformed_selectors[payload4]': _R['R23'],
    'tests/test_payment_hardening.py::test_paypal_refund_webhook_reverses_rtc_balance_once': _R['R24'],
    'tests/test_payment_hardening.py::test_store_capture_credits_agent_balance_and_earnings': _R['R24'],
    'tests/test_payment_hardening.py::test_x402_accepts_caip2_network_in_receipt': _R['R24'],
    'tests/test_payment_hardening.py::test_x402_requires_structured_receipt_and_blocks_cross_endpoint_replay': _R['R24'],
    'tests/test_payment_hardening.py::test_x402_stats_has_no_rtc_reference_rate': _R['R24'],
    'tests/test_playlist_visibility.py::test_playlist_append_allocates_unique_positions_concurrently': _R['R25'],
    'tests/test_playlist_visibility.py::test_playlist_append_duplicate_race_returns_conflict_sentinel': _R['R25'],
    'tests/test_quests.py::test_comment_vote_application_recovers_from_stale_existing_snapshot': _R['R26'],
    'tests/test_referrals.py::test_referral_first_upload_is_counted_once_under_concurrent_stale_reads': _R['R27'],
    'tests/test_referrals.py::test_referral_hit_window_is_admitted_once_under_concurrent_stale_reads[expired-window]': _R['R27'],
    'tests/test_referrals.py::test_referral_hit_window_is_admitted_once_under_concurrent_stale_reads[new-fingerprint]': _R['R27'],
    'tests/test_search_filter_sort_state.py::test_search_category_control_filters_and_likes_sort_orders': _R['R28'],
    'tests/test_search_filter_sort_state.py::test_search_pagination_preserves_category_and_sort': _R['R28'],
    'tests/test_search_suggestions_contract.py::test_search_suggestions_are_bounded_for_non_queries': _R['R29'],
    'tests/test_search_suggestions_contract.py::test_search_suggestions_return_public_catalog_matches': _R['R29'],
    'tests/test_studio_poll_contract.py::test_poll_finishes_a_valid_completed_video_response': _R['R30'],
    'tests/test_subscribe_result_contract.py::test_subscribe_handlers_preserve_state_and_report_every_outcome[path0-toggleSubscribe-None-subscribe-btn-subscribe-status-sub-count]': _R['R31'],
    'tests/test_subscribe_result_contract.py::test_subscribe_results_are_atomic_live_statuses': _R['R31'],
    'tests/test_syndication_poller.py::test_process_pending_items_completes_dequeued_item_without_re_marking_processing': _R['R32'],
    'tests/test_syndication_poller.py::test_queue_new_videos_applies_agent_platform_overrides': _R['R32'],
    'tests/test_syndication_poller.py::test_reload_runtime_config_rebuilds_adapters_and_updates_poll_interval': _R['R32'],
    'tests/test_syndication_routes.py::test_export_route_returns_inline_json_without_file_path': _R['R33'],
    'tests/test_syndication_routes.py::test_numeric_query_params_reject_malformed_values[/api/syndication/report/export?type=outbound&days=not-an-int]': _R['R33'],
    'tests/test_syndication_routes.py::test_numeric_query_params_reject_malformed_values[/api/syndication/report/outbound?days=not-an-int]': _R['R33'],
    'tests/test_syndication_routes.py::test_numeric_query_params_reject_malformed_values[/api/syndication/runs?days=not-an-int]': _R['R33'],
    'tests/test_syndication_routes.py::test_numeric_query_params_reject_malformed_values[/api/syndication/runs?limit=not-an-int]': _R['R33'],
    'tests/test_syndication_routes.py::test_report_routes_reject_malformed_dates[/api/syndication/report/daily?date=not-a-date]': _R['R33'],
    'tests/test_syndication_routes.py::test_report_routes_reject_malformed_dates[/api/syndication/report/export?type=daily&date=not-a-date]': _R['R33'],
    'tests/test_syndication_routes.py::test_report_routes_reject_malformed_dates[/api/syndication/report/export?type=weekly&end_date=not-a-date]': _R['R33'],
    'tests/test_syndication_routes.py::test_report_routes_reject_malformed_dates[/api/syndication/report/weekly?end_date=not-a-date]': _R['R33'],
    'tests/test_syndication_routes.py::test_report_routes_scope_normal_agents_and_expand_for_admin': _R['R33'],
    'tests/test_syndication_routes.py::test_update_item_requires_owner_scope': _R['R33'],
    'tests/test_syndication_routes.py::test_write_routes_reject_non_object_json[post-/api/syndication/item-payload2]': _R['R33'],
    'tests/test_syndication_routes.py::test_write_routes_reject_non_object_json[post-/api/syndication/run/1/end-payload1]': _R['R33'],
    'tests/test_syndication_routes.py::test_write_routes_reject_non_object_json[post-/api/syndication/run/start-payload0]': _R['R33'],
    'tests/test_syndication_routes.py::test_write_routes_reject_non_object_json[put-/api/syndication/item/1-payload3]': _R['R33'],
    'tests/test_tip_message_json_validation.py::test_tip_routes_reject_structured_message_without_moving_credits[/api/agents/tiptarget/tip-False]': _R['R34'],
    'tests/test_tip_message_json_validation.py::test_tip_routes_reject_structured_message_without_moving_credits[/api/agents/tiptarget/web-tip-True]': _R['R34'],
    'tests/test_tip_message_json_validation.py::test_tip_routes_reject_structured_message_without_moving_credits[/api/videos/tipvideo01AB/tip-False]': _R['R34'],
    'tests/test_tip_message_json_validation.py::test_tip_routes_reject_structured_message_without_moving_credits[/api/videos/tipvideo01AB/web-tip-True]': _R['R34'],
    'tests/test_upload_api.py::TestUploadIntegration::test_uploaded_video_appears_in_agent_profile': _R['R35'],
    'tests/test_upload_api.py::TestUploadIntegration::test_uploaded_video_appears_in_listing': _R['R35'],
    'tests/test_upload_api.py::TestUploadIntegration::test_uploaded_video_detail_endpoint': _R['R35'],
    'tests/test_upload_api.py::TestUploadMetadata::test_invalid_category_defaults_to_other': _R['R35'],
    'tests/test_upload_api.py::TestUploadMetadata::test_tags_parsed_from_csv': _R['R35'],
    'tests/test_user_route_aliases_1362_1371.py::test_me_redirects_anonymous_to_login': _R['R36'],
    'tests/test_user_route_aliases_1362_1371.py::test_settings_redirects_anonymous_to_login': _R['R36'],
    'tests/test_user_route_aliases_1362_1371.py::test_wallet_redirects_anonymous_to_login': _R['R36'],
    'tests/test_video_tips_api.py::test_video_tips_rejects_invalid_pagination_before_lookup': _R['R38'],
    'tests/test_wrtc_bridge_validation.py::test_bridge_landing_handles_user_with_null_sol_address': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_bridge_landing_passes_template_context_for_anonymous_user': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_bridge_landing_uses_authenticated_user_balance_and_sol_address': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_rejected_wrtc_withdrawal_does_not_queue_or_debit': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_deposit_rejects_non_object_json': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_deposit_rejects_non_string_tx_signature': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_history_rejects_invalid_limit[-5]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_history_rejects_invalid_limit[0]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_history_rejects_invalid_limit[1.5]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_history_rejects_invalid_limit[not-a-number]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_history_rejects_invalid_limit[true]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_html_alias_routes_redirect_to_bridge_console[/premium/wrtc]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_html_alias_routes_redirect_to_bridge_console[/wrtc/deposit]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_html_alias_routes_redirect_to_bridge_console[/wrtc/history]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_html_alias_routes_redirect_to_bridge_console[/wrtc/withdraw]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_html_alias_routes_redirect_to_bridge_console[/wrtc]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_finite_amounts[Infinity]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_finite_amounts[NaN]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_finite_amounts[True]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_finite_amounts[abc]': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_object_json': _R['R11'],
    'tests/test_wrtc_bridge_validation.py::test_wrtc_withdraw_rejects_non_string_to_address': _R['R11'],
}
