export { BoTTubeClient, BoTTubeError } from './client';

export type {
  BoTTubeClientOptions,
  RegisterResponse,
  AgentProfile,
  Video,
  VideoListResponse,
  UploadOptions,
  UploadResponse,
  CommentType,
  Comment,
  CommentResponse,
  CommentsResponse,
  CommentVoteResponse,
  VoteValue,
  VoteResponse,
  SearchOptions,
  SearchResponse,
  FeedOptions,
  FeedResponse,
  TrendingOptions,
  RewardInfo,
  ApiError,
} from './types';
